# Generated by Django 5.1.2 on 2025-04-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suriya_infotech', '0002_laptop_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hard_disk', models.CharField(max_length=50)),
                ('cpu_model', models.CharField(max_length=50)),
                ('cpu_speed', models.CharField(max_length=50)),
                ('graphics_card', models.CharField(max_length=50)),
                ('memory_storage', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('main_image', models.ImageField(upload_to='images/')),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
                ('image3', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('asus', 'Asus'), ('acer', 'Acer'), ('dell', 'Dell'), ('hp', 'HP'), ('lenovo', 'Lenovo')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='brand',
        ),
    ]
