# Generated by Django 5.1.2 on 2025-04-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suriya_infotech', '0003_desktop_remove_laptop_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refurbished_Desktop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hard_disk', models.CharField(max_length=50)),
                ('cpu_model', models.CharField(max_length=50)),
                ('cpu_speed', models.CharField(max_length=50)),
                ('graphics_card', models.CharField(max_length=50)),
                ('memory_storage', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('main_image', models.ImageField(upload_to='images/refurbished_desktop/')),
                ('image1', models.ImageField(upload_to='images/refurbished_desktop/')),
                ('image2', models.ImageField(upload_to='images/refurbished_desktop/')),
                ('image3', models.ImageField(upload_to='images/refurbished_desktop/')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('asus', 'Asus'), ('acer', 'Acer'), ('dell', 'Dell'), ('hp', 'HP'), ('lenovo', 'Lenovo')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Refurbished_Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('screen_size', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('hard_disk', models.CharField(max_length=50)),
                ('cpu_model', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('main_image', models.ImageField(upload_to='images/refurbished_laptop/')),
                ('image1', models.ImageField(upload_to='images/refurbished_laptop/')),
                ('image2', models.ImageField(upload_to='images/refurbished_laptop/')),
                ('image3', models.ImageField(upload_to='images/refurbished_laptop/')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('asus', 'Asus'), ('acer', 'Acer'), ('dell', 'Dell'), ('hp', 'HP'), ('lenovo', 'Lenovo'), ('samsung', 'Samsung'), ('apple', 'Apple')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='desktop',
            name='image1',
            field=models.ImageField(upload_to='images/desktop/'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='image2',
            field=models.ImageField(upload_to='images/desktop/'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='image3',
            field=models.ImageField(upload_to='images/desktop/'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='main_image',
            field=models.ImageField(upload_to='images/desktop/'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='image1',
            field=models.ImageField(upload_to='images/laptop/'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='image2',
            field=models.ImageField(upload_to='images/laptop/'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='image3',
            field=models.ImageField(upload_to='images/laptop/'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='main_image',
            field=models.ImageField(upload_to='images/laptop/'),
        ),
    ]
