# Generated by Django 5.1.2 on 2025-04-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suriya_infotech', '0004_refurbished_desktop_refurbished_laptop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ink_printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brands', models.CharField(choices=[('epson', 'Epson'), ('canon', 'Canon'), ('brother', 'Brother'), ('hp', 'HP')], max_length=50)),
                ('connectivity', models.CharField(max_length=50)),
                ('printing_technology', models.CharField(max_length=50)),
                ('special_features', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('print_speed', models.CharField(max_length=50)),
                ('item_weight', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('main_image', models.ImageField(upload_to='images/ink_printer/')),
                ('image1', models.ImageField(upload_to='images/ink_printer/')),
                ('image2', models.ImageField(upload_to='images/ink_printer/')),
                ('image3', models.ImageField(upload_to='images/ink_printer/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Laser_Jet_printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brands', models.CharField(choices=[('canon', 'Canon'), ('brother', 'Brother'), ('hp', 'HP')], max_length=50)),
                ('connectivity', models.CharField(max_length=50)),
                ('Special_features', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('printer_output', models.CharField(max_length=50)),
                ('item_weight', models.CharField(max_length=50)),
                ('max_speed', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('main_image', models.ImageField(upload_to='images/laser_printer/')),
                ('image1', models.ImageField(upload_to='images/laser_printer/')),
                ('image2', models.ImageField(upload_to='images/laser_printer/')),
                ('image3', models.ImageField(upload_to='images/laser_printer/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Thermal_printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brands', models.CharField(choices=[('rugtek', 'Rugtek'), ('tvs', 'TVS')], max_length=50)),
                ('connectivity', models.CharField(max_length=50)),
                ('technology', models.CharField(max_length=50)),
                ('special_features', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('printer_output', models.CharField(max_length=50)),
                ('print_speed', models.CharField(max_length=50)),
                ('item_weight', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('main_image', models.ImageField(upload_to='images/thermal_printer/')),
                ('image1', models.ImageField(upload_to='images/thermal_printer/')),
                ('image2', models.ImageField(upload_to='images/thermal_printer/')),
                ('image3', models.ImageField(upload_to='images/thermal_printer/')),
                ('description', models.TextField()),
            ],
        ),
    ]
